# ASTM E2022

In [1]:
from __future__ import division

import numpy as np
import pandas as pd
from scipy.interpolate import lagrange

import colour
from colour import CaseInsensitiveMapping, SpectralShape, tstack

np.set_printoptions(suppress=True)

SPD_DATA = {
    360: 0.004880,
    361: 0.004595,
    362: 0.004310,
    363: 0.020290,
    364: 0.036270,
    365: 0.047350,
    366: 0.058440,
    367: 0.031870,
    368: 0.005300,
    369: 0.004700,
    370: 0.004100,
    371: 0.003785,
    372: 0.003470,
    373: 0.003540,
    374: 0.003610,
    375: 0.003615,
    376: 0.003620,
    377: 0.004210,
    378: 0.004800,
    379: 0.005170,
    380: 0.005540,
    381: 0.005240,
    382: 0.004940,
    383: 0.004615,
    384: 0.004290,
    385: 0.003750,
    386: 0.003210,
    387: 0.003050,
    388: 0.002890,
    389: 0.002980,
    390: 0.003070,
    391: 0.002795,
    392: 0.002520,
    393: 0.002395,
    394: 0.002270,
    395: 0.002285,
    396: 0.002300,
    397: 0.002420,
    398: 0.002540,
    399: 0.002640,
    400: 0.002740,
    401: 0.002845,
    402: 0.002950,
    403: 0.062430,
    404: 0.121900,
    405: 0.085640,
    406: 0.049360,
    407: 0.032040,
    408: 0.014720,
    409: 0.009680,
    410: 0.004640,
    411: 0.005120,
    412: 0.005600,
    413: 0.005835,
    414: 0.006070,
    415: 0.006515,
    416: 0.006960,
    417: 0.007105,
    418: 0.007250,
    419: 0.007345,
    420: 0.007440,
    421: 0.007790,
    422: 0.008140,
    423: 0.008565,
    424: 0.008990,
    425: 0.009260,
    426: 0.009530,
    427: 0.009820,
    428: 0.010110,
    429: 0.010520,
    430: 0.010930,
    431: 0.011280,
    432: 0.011630,
    433: 0.020610,
    434: 0.029590,
    435: 0.241400,
    436: 0.453200,
    437: 0.233900,
    438: 0.014620,
    439: 0.014530,
    440: 0.014450,
    441: 0.014400,
    442: 0.014340,
    443: 0.014430,
    444: 0.014510,
    445: 0.014490,
    446: 0.014470,
    447: 0.014650,
    448: 0.014820,
    449: 0.014850,
    450: 0.014870,
    451: 0.015040,
    452: 0.015210,
    453: 0.014980,
    454: 0.014750,
    455: 0.014370,
    456: 0.014000,
    457: 0.014060,
    458: 0.014110,
    459: 0.013930,
    460: 0.013760,
    461: 0.013470,
    462: 0.013180,
    463: 0.013470,
    464: 0.013750,
    465: 0.014000,
    466: 0.014250,
    467: 0.013810,
    468: 0.013370,
    469: 0.012870,
    470: 0.012370,
    471: 0.012640,
    472: 0.012900,
    473: 0.012640,
    474: 0.012380,
    475: 0.011680,
    476: 0.010970,
    477: 0.011050,
    478: 0.011130,
    479: 0.012680,
    480: 0.014240,
    481: 0.019080,
    482: 0.023910,
    483: 0.035600,
    484: 0.047290,
    485: 0.064030,
    486: 0.080770,
    487: 0.082540,
    488: 0.084310,
    489: 0.073870,
    490: 0.063440,
    491: 0.059500,
    492: 0.055560,
    493: 0.049350,
    494: 0.043140,
    495: 0.038320,
    496: 0.033490,
    497: 0.030100,
    498: 0.026710,
    499: 0.023390,
    500: 0.020080,
    501: 0.017300,
    502: 0.014520,
    503: 0.012700,
    504: 0.010870,
    505: 0.009670,
    506: 0.008470,
    507: 0.008350,
    508: 0.008230,
    509: 0.007905,
    510: 0.007580,
    511: 0.007370,
    512: 0.007160,
    513: 0.006895,
    514: 0.006630,
    515: 0.006435,
    516: 0.006240,
    517: 0.006200,
    518: 0.006160,
    519: 0.006355,
    520: 0.006550,
    521: 0.006560,
    522: 0.006570,
    523: 0.006590,
    524: 0.006610,
    525: 0.007150,
    526: 0.007690,
    527: 0.008285,
    528: 0.008880,
    529: 0.009030,
    530: 0.009180,
    531: 0.011460,
    532: 0.013750,
    533: 0.018810,
    534: 0.023880,
    535: 0.024380,
    536: 0.024890,
    537: 0.044580,
    538: 0.064270,
    539: 0.113300,
    540: 0.162400,
    541: 0.277600,
    542: 0.392800,
    543: 0.353900,
    544: 0.315100,
    545: 0.429800,
    546: 0.544600,
    547: 0.383500,
    548: 0.222500,
    549: 0.182100,
    550: 0.141700,
    551: 0.113500,
    552: 0.085290,
    553: 0.070050,
    554: 0.054810,
    555: 0.046030,
    556: 0.037250,
    557: 0.034310,
    558: 0.031360,
    559: 0.030480,
    560: 0.029590,
    561: 0.029650,
    562: 0.029700,
    563: 0.029530,
    564: 0.029360,
    565: 0.029200,
    566: 0.029040,
    567: 0.029500,
    568: 0.029960,
    569: 0.029480,
    570: 0.029000,
    571: 0.029140,
    572: 0.029280,
    573: 0.029390,
    574: 0.029500,
    575: 0.040510,
    576: 0.051530,
    577: 0.060840,
    578: 0.070160,
    579: 0.079050,
    580: 0.087930,
    581: 0.090370,
    582: 0.092820,
    583: 0.098470,
    584: 0.104100,
    585: 0.102800,
    586: 0.101400,
    587: 0.113700,
    588: 0.126000,
    589: 0.097210,
    590: 0.068430,
    591: 0.085320,
    592: 0.102200,
    593: 0.103800,
    594: 0.105400,
    595: 0.083490,
    596: 0.061600,
    597: 0.064520,
    598: 0.067430,
    599: 0.077740,
    600: 0.088050,
    601: 0.068570,
    602: 0.049080,
    603: 0.047100,
    604: 0.045120,
    605: 0.048080,
    606: 0.051040,
    607: 0.065430,
    608: 0.079820,
    609: 0.231200,
    610: 0.382600,
    611: 0.600400,
    612: 0.818300,
    613: 0.558200,
    614: 0.298100,
    615: 0.223100,
    616: 0.148200,
    617: 0.112500,
    618: 0.076780,
    619: 0.074490,
    620: 0.072200,
    621: 0.075760,
    622: 0.079320,
    623: 0.084640,
    624: 0.089950,
    625: 0.090240,
    626: 0.090530,
    627: 0.085950,
    628: 0.081370,
    629: 0.096260,
    630: 0.111200,
    631: 0.102900,
    632: 0.094620,
    633: 0.062350,
    634: 0.030080,
    635: 0.027420,
    636: 0.024770,
    637: 0.023050,
    638: 0.021330,
    639: 0.020750,
    640: 0.020170,
    641: 0.019920,
    642: 0.019660,
    643: 0.019740,
    644: 0.019810,
    645: 0.019550,
    646: 0.019280,
    647: 0.019080,
    648: 0.018880,
    649: 0.030460,
    650: 0.042050,
    651: 0.034870,
    652: 0.027690,
    653: 0.024990,
    654: 0.022290,
    655: 0.020120,
    656: 0.017950,
    657: 0.019130,
    658: 0.020320,
    659: 0.017400,
    660: 0.014470,
    661: 0.020750,
    662: 0.027030,
    663: 0.022910,
    664: 0.018790,
    665: 0.015270,
    666: 0.011740,
    667: 0.012890,
    668: 0.014040,
    669: 0.013040,
    670: 0.012030,
    671: 0.012230,
    672: 0.012430,
    673: 0.011550,
    674: 0.010680,
    675: 0.010140,
    676: 0.009600,
    677: 0.009705,
    678: 0.009810,
    679: 0.010690,
    680: 0.011560,
    681: 0.010990,
    682: 0.010420,
    683: 0.010040,
    684: 0.009650,
    685: 0.012730,
    686: 0.015810,
    687: 0.021660,
    688: 0.027500,
    689: 0.018370,
    690: 0.009240,
    691: 0.008135,
    692: 0.007030,
    693: 0.013520,
    694: 0.020020,
    695: 0.013810,
    696: 0.007600,
    697: 0.005805,
    698: 0.004010,
    699: 0.003575,
    700: 0.003140,
    701: 0.005040,
    702: 0.006940,
    703: 0.008540,
    704: 0.010140,
    705: 0.024700,
    706: 0.039250,
    707: 0.047360,
    708: 0.055470,
    709: 0.047700,
    710: 0.039920,
    711: 0.047550,
    712: 0.055180,
    713: 0.033360,
    714: 0.011550,
    715: 0.007855,
    716: 0.004160,
    717: 0.002845,
    718: 0.001530,
    719: 0.002970,
    720: 0.004410,
    721: 0.003505,
    722: 0.002600,
    723: 0.002470,
    724: 0.002340,
    725: 0.002375,
    726: 0.002410,
    727: 0.002450,
    728: 0.002490,
    729: 0.001795,
    730: 0.001100,
    731: 0.001120,
    732: 0.001140,
    733: 0.001750,
    734: 0.002360,
    735: 0.002190,
    736: 0.002020,
    737: 0.003930,
    738: 0.005840,
    739: 0.003355,
    740: 0.000870,
    741: 0.002235,
    742: 0.003600,
    743: 0.002500,
    744: 0.001400,
    745: 0.002155,
    746: 0.002910,
    747: 0.002970,
    748: 0.003030,
    749: 0.003615,
    750: 0.004200,
    751: 0.003470,
    752: 0.002740,
    753: 0.002225,
    754: 0.001710,
    755: 0.000855,
    756: 0.000000,
    757: 0.000310,
    758: 0.000620,
    759: 0.000310,
    760: 0.000000,
    761: 0.000000,
    762: 0.000000,
    763: 0.000000,
    764: 0.000000,
    765: 0.000000,
    766: 0.000000,
    767: 0.000000,
    768: 0.000000,
    769: 0.000000,
    770: 0.000000,
    771: 0.000000,
    772: 0.000000,
    773: 0.000000,
    774: 0.000000,
    775: 0.000000,
    776: 0.000000,
    777: 0.000000,
    778: 0.000000,
    779: 0.000000,
    780: 0.000000,
    781: 0.000000,
    782: 0.000000,
    783: 0.000000,
    784: 0.000000,
    785: 0.000000,
    786: 0.000000,
    787: 0.000000,
    788: 0.000000,
    789: 0.000000,
    790: 0.000000,
    791: 0.000000,
    792: 0.000000,
    793: 0.000000,
    794: 0.000000,
    795: 0.000000,
    796: 0.000000,
    797: 0.000000,
    798: 0.000000,
    799: 0.000000,
    800: 0.000000,
    801: 0.000000,
    802: 0.000000,
    803: 0.000000,
    804: 0.000000,
    805: 0.000000,
    806: 0.000000,
    807: 0.000000,
    808: 0.000000,
    809: 0.000000,
    810: 0.000000,
    811: 0.000000,
    812: 0.000000,
    813: 0.000000,
    814: 0.000000,
    815: 0.000000,
    816: 0.000000,
    817: 0.000000,
    818: 0.000000,
    819: 0.000000,
    820: 0.000000,
    821: 0.000000,
    822: 0.000000,
    823: 0.000000,
    824: 0.000000,
    825: 0.000000,
    826: 0.000000,
    827: 0.000000,
    828: 0.000000,
    829: 0.000000,
    830: 0.000000}

SPD = colour.SpectralPowerDistribution('SPD', SPD_DATA)

CMFS = colour.STANDARD_OBSERVERS_CMFS.get(
        'CIE 1964 10 Degree Standard Observer')

def _A(w):
    return (100 * (560 / w) ** 5 * (
        ((np.exp((1.435 * 10 ** 7) / (2848 * 560)) - 1) /
         (np.exp((1.435 * 10 ** 7) / (2848 * w)) - 1))))

A = colour.SpectralPowerDistribution('A', dict(zip(CMFS.shape.range(),
                                                  _A(CMFS.shape.range()))))

_TRISTIMULUS_WEIGHTING_FACTORS_CACHE = None

_LAGRANGE_INTERPOLATING_COEFFICIENTS_CACHE = None


def lagrange_interpolating_coefficient(r, d=4):
    r_i = np.arange(d)
    L_n = []
    for j in range(len(r_i)):
        p = [(r - r_i[m]) / (r_i[j] - r_i[m])
             for m in range(len(r_i)) if m != j]
        L_n.append(reduce(lambda m, n: m * n, p))

    return L_n


def lagrange_interpolating_coefficients_ASTME2022(steps=10,
                                                  interval='intermediate'):
    global _LAGRANGE_INTERPOLATING_COEFFICIENTS_CACHE
    if _LAGRANGE_INTERPOLATING_COEFFICIENTS_CACHE is None:
        _LAGRANGE_INTERPOLATING_COEFFICIENTS_CACHE = CaseInsensitiveMapping()

    name_lica = ', '.join((str(steps), interval))
    if name_lica in _LAGRANGE_INTERPOLATING_COEFFICIENTS_CACHE:
        return _LAGRANGE_INTERPOLATING_COEFFICIENTS_CACHE[name_lica]

    r_n = np.linspace(1 / steps, 1 - (1 / steps), steps - 1)
    d = 3
    if interval.lower() == 'intermediate':
        r_n += 1
        d = 4

    lica = _LAGRANGE_INTERPOLATING_COEFFICIENTS_CACHE[name_lica] = (
        np.asarray([lagrange_interpolating_coefficient(r, d) for r in r_n]))

    return lica

In [2]:
def tristimulus_weighting_factors_ASTME2022(cmfs, illuminant, shape):
    # Assumes that the measurement interval is equal to the spectral bandwidth integral when applying correction
    # for bandwidth.
    if cmfs.shape.steps != 1:
        raise RuntimeError('"{0}" shape "steps" must be 1!'.format(cmfs))

    if illuminant.shape.steps != 1:
        raise RuntimeError('"{0}" shape "steps" must be 1!'.format(illuminant))

    global _TRISTIMULUS_WEIGHTING_FACTORS_CACHE
    if _TRISTIMULUS_WEIGHTING_FACTORS_CACHE is None:
        _TRISTIMULUS_WEIGHTING_FACTORS_CACHE = CaseInsensitiveMapping()

    name_twf = ', '.join((cmfs.name, illuminant.name, str(shape)))
    if name_twf in _TRISTIMULUS_WEIGHTING_FACTORS_CACHE:
        return _TRISTIMULUS_WEIGHTING_FACTORS_CACHE[name_twf]

    Y = cmfs.values
    S = illuminant.values

    W = S[::shape.steps, np.newaxis] * Y[::shape.steps, :]

    # First and last measurement intervals Lagrange interpolating coefficients.
    c_c = lagrange_interpolating_coefficients_ASTME2022(
            shape.steps, 'boundaries')
    # Intermediate measurement intervals Lagrange interpolating coefficients.
    c_b = lagrange_interpolating_coefficients_ASTME2022(
            shape.steps, 'intermediate')

    # Total wavelengths count.
    w_c = len(Y)
    # Measurement interval interpolated values count.
    r_c = c_b.shape[0]
    # Last interval first interpolated wavelength.
    w_lif = w_c - (w_c - 1) % shape.steps - 1 - r_c

    # Intervals count.
    i_c = W.shape[0]
    i_cm = i_c - 1

    for i in range(3):
        # First interval.
        for j in range(r_c):
            for k in range(3):
                W[k, i] = W[k, i] + c_c[j, k] * S[j + 1] * Y[j + 1, i]

        # Last interval.
        for j in range(r_c):
            for k in range(i_cm, i_cm - 3, -1):
                W[k, i] = (W[k, i] + c_c[r_c - j - 1, i_cm - k] *
                           S[j + w_lif] * Y[j + w_lif, i])

        # Intermediate intervals.
        for j in range(i_c - 3):
            for k in range(r_c):
                w_i = (r_c + 1) * (j + 1) + 1 + k
                W[j, i] = W[j, i] + c_b[k, 0] * S[w_i] * Y[w_i, i]
                W[j + 1, i] = W[j + 1, i] + c_b[k, 1] * S[w_i] * Y[w_i, i]
                W[j + 2, i] = W[j + 2, i] + c_b[k, 2] * S[w_i] * Y[w_i, i]
                W[j + 3, i] = W[j + 3, i] + c_b[k, 3] * S[w_i] * Y[w_i, i]

        # Extrapolation of incomplete interval.
        for j in range(int(w_c - ((w_c - 1) % shape.steps)), w_c, 1):
            W[i_cm, i] = W[i_cm, i] + S[j] * Y[j, i]

    W *= 100 / np.sum(W, axis=0)[1]
    
    _TRISTIMULUS_WEIGHTING_FACTORS_CACHE[name_twf] = W

    return W


steps = 10
W = tristimulus_weighting_factors_ASTME2022(
        CMFS, A, SpectralShape(360, 830, steps))
pd.DataFrame(np.round(W, 3), index=CMFS.wavelengths[::steps])

/anaconda/envs/colour-2.7/lib/python2.7/site-packages/ipykernel/__main__.py:21: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
/anaconda/envs/colour-2.7/lib/python2.7/site-packages/ipykernel/__main__.py:51: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


0      1      2
360  -0.000 -0.000 -0.000
370  -0.000 -0.000 -0.000
380  -0.000 -0.000 -0.000
390   0.002  0.000  0.008
400   0.025  0.003  0.110
410   0.134  0.014  0.615
420   0.377  0.039  1.792
430   0.686  0.084  3.386
440   0.964  0.156  4.944
450   1.080  0.259  5.806
460   1.006  0.424  5.812
470   0.731  0.696  4.919
480   0.343  1.082  3.300
490   0.078  1.616  1.973
500   0.022  2.422  1.152
510   0.218  3.529  0.658
520   0.750  4.840  0.382
530   1.642  6.100  0.211
540   2.842  7.250  0.102
550   4.336  8.114  0.032
560   6.200  8.758  0.001
570   8.262  8.988 -0.000
580  10.227  8.760  0.000
590  11.945  8.304  0.000
600  12.746  7.468  0.000
610  12.337  6.323  0.000
620  10.817  5.033  0.000
630   8.560  3.744  0.000
640   6.014  2.506  0.000
650   3.887  1.560  0.000
660   2.309  0.911  0.000
670   1.276  0.499  0.000
680   0.666  0.259  0.000
690   0.336  0.130  0.000
700   0.166  0.065  0.000
710   0.082  0.032  0.000
720   0.040  0.016  0.000
730   0.020  0.008  0.000
740   0.010  0.004  0.000
750   0.005  0.002  0.000
760   0.003  0.001  0.000
770   0.001  0.001  0.000
780   0.001  0.000  0.000
790   0.000  0.000  0.000
800   0.000  0.000  0.000
810   0.000  0.000  0.000
820   0.000  0.000  0.000
830   0.000  0.000  0.000

In [3]:
_TRISTIMULUS_WEIGHTING_FACTORS_CACHE.keys()

[u'CIE 1964 10 Degree Standard Observer, A, (360.0, 830.0, 10.0)']

In [4]:
class LagrangeInterpolator_ASTM2022(object):
    """
    Parameters
    ----------
    x : array_like
        Independent :math:`x` variable values corresponding with :math:`y`
        variable.
    y : array_like
        Dependent and already known :math:`y` variable values to
        interpolate.

    Methods
    -------
    __call__

    See Also
    --------
    LinearInterpolator

    Notes
    -----
    The minimum number :math:`k` of data points required along the
    interpolation axis is :math:`k=6`.

    References
    ----------

    Examples
    --------
    Interpolating a single numeric variable:

    >>> y = np.array([5.9200,
    ...               9.3700,
    ...               10.8135,
    ...               4.5100,
    ...               69.5900,
    ...               27.8007,
    ...               86.0500])
    >>> x = np.arange(len(y))
    >>> f = LagrangeInterpolator_ASTM2022(x, y)
    >>> f(0.5)  # doctest: +ELLIPSIS
    7.2185025...

    Interpolating an *array_like* variable:

    >>> f([0.25, 0.75])  # doctest: +ELLIPSIS
    array([ 6.7295161...,  7.8140625...])
    """

    def __init__(self, x=None, y=None):
        self.__x = None
        self.x = x
        self.__y = None
        self.y = y

        self.__validate_dimensions()

    @property
    def x(self):
        """
        Property for **self.__x** private attribute.

        Returns
        -------
        array_like
            self.__x
        """

        return self.__x

    @x.setter
    def x(self, value):
        """
        Setter for **self.__x** private attribute.

        Parameters
        ----------
        value : array_like
            Attribute value.
        """

        if value is not None:
            value = np.atleast_1d(value).astype(np.float_)

            assert value.ndim == 1, (
                '"x" independent variable must have exactly one dimension!')

        self.__x = value

    @property
    def y(self):
        """
        Property for **self.__y** private attribute.

        Returns
        -------
        array_like
            self.__y
        """

        return self.__y

    @y.setter
    def y(self, value):
        """
        Setter for **self.__y** private attribute.

        Parameters
        ----------
        value : array_like
            Attribute value.
        """

        if value is not None:
            value = np.atleast_1d(value).astype(np.float_)

            assert value.ndim == 1, (
                '"y" dependent variable must have exactly one dimension!')

            assert len(value) >= 3, (
                '"y" dependent variable values count must be in domain [3:]!')

        self.__y = value

    def __call__(self, x):
        """
        Evaluates the interpolating polynomial at given point(s).

        Parameters
        ----------
        x : numeric or array_like
            Point(s) to evaluate the interpolant at.

        Returns
        -------
        numeric or ndarray
            Interpolated value(s).
        """

        return self.__evaluate(x)

    def __evaluate(self, x):
        """
        Performs the interpolating polynomial evaluation at given point.

        Parameters
        ----------
        x : numeric
            Point to evaluate the interpolant at.

        Returns
        -------
        float
            Interpolated point values.
        """

        x = np.atleast_1d(x)

        self.__validate_dimensions()
        self.__validate_interpolation_range(x)

        y = []
        indexes = np.searchsorted(self.__x, x) - 1
        for i, ii in enumerate(indexes):
            if ii == 0:
                p = [ii, ii + 1, ii + 2]
            elif ii == len(self.__x) - 2:
                p = [ii - 1, ii, ii + 1]
            else:
                p = [ii - 1, ii, ii + 1, ii + 2]

            y.append(lagrange(self.__x[p], self.__y[p])(x[i]))

        return np.array(y)

    def __validate_dimensions(self):
        """
        Validates variables dimensions to be the same.
        """

        if len(self.__x) != len(self.__y):
            raise ValueError(
                ('"x" independent and "y" dependent variables have different '
                 'dimensions: "{0}", "{1}"').format(len(self.__x),
                                                    len(self.__y)))

    def __validate_interpolation_range(self, x):
        """
        Validates given point to be in interpolation range.
        """

        below_interpolation_range = x < self.__x[0]
        above_interpolation_range = x > self.__x[-1]

        if below_interpolation_range.any():
            raise ValueError('"{0}" is below interpolation range.'.format(x))

        if above_interpolation_range.any():
            raise ValueError('"{0}" is above interpolation range.'.format(x))


y = np.array([5.9200, 9.3700, 10.8135, 4.5100, 6.5900, 7.8007, 8.0500])
x = np.arange(len(y))
print(x)
n = 2.5
print(LagrangeInterpolator_ASTM2022(x, y)(n))
print(colour.LinearInterpolator(x, y)(n))
print(colour.SpragueInterpolator(x, y)(n))
print(colour.CubicSplineInterpolator(x, y)(n))

print('\n')
n = (0.1, 2.5, 3.5, 5.9)
print(LagrangeInterpolator_ASTM2022(x, y)(n))
print(colour.LinearInterpolator(x, y)(n))
print(colour.SpragueInterpolator(x, y)(n))
print(colour.CubicSplineInterpolator(x, y)(n))

print('\n')

y = np.array([5.9200, 9.3700, 10.8135])
x = np.arange(len(y))
print(LagrangeInterpolator_ASTM2022(x, y)((1, 1, 1, 1)))

[0 1 2 3 4 5 6]
[ 7.62196875]
7.66175
7.58080898437
7.49388148193


[ 6.3552925   7.62196875  5.0803625   8.068333  ]
[ 6.265    7.66175  5.55     8.02507]
[ 6.26844724  7.58080898  4.89025391  8.03687569]
[ 5.73319701  7.49388148  4.76535906  7.77059769]


[ 9.37  9.37  9.37  9.37]


In [5]:
S0 = colour.D_ILLUMINANTS_S_SPDS['S0']
x = S0.wavelengths
y = S0.values

n = 825

print(colour.LinearInterpolator(x, y)(n))
print(LagrangeInterpolator_ASTM2022(x, y)(n))
print(colour.CubicSplineInterpolator(x, y)(n))
print(colour.SpragueInterpolator(x, y)(n))

60.4
[ 60.725]
62.6293978601
60.997850628
